# render.yaml

services:
  - name: client
    type: web
    buildCommand: npm install && cd client && npm run build
    startCommand: cd client && npm run start
    env:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: npm install && cd server && npm run build
    startCommand: cd server && npm run start
    env:
      - key: NODE_ENV
        value: production

database:
  - name: mongodb
    type: mongodb
    env:
      - key: MONGODB_URI
        fromDatabase:
          name: your-database-name
          property: connectionString
