# render.yaml

services:
  - name: client
    type: web
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: |
      cd server
      npm install
      npm run build
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production

database:
  - name: mongodb
    type: mongodb
    env:
      - key: MONGODB_URI
        fromDatabase:
          name: your-database-name
          property: connectionString
