# render.yaml

services:
  - name: client
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    workingDirectory: /opt/render/project/client
    env:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    workingDirectory: /opt/render/project/server
    env:
      - key: NODE_ENV
        value: production

database:
  - name: mongodb
    type: mongodb
    env:
      - key: MONGODB_URI
        fromDatabase:
          name: your-database-name
          property: connectionString
